import { vec } from 'excalibur';
import { tilePos } from '../utils';
import { RouteIndexicalSymbol, RoutePath } from './forklift2';

export const routePathMap: Record<RouteIndexicalSymbol, Readonly<RoutePath>> = {
  srbay0_shelf0: [
    tilePos(vec(0, 0), 'center'),
    tilePos(vec(0, 0), 'cr'),
    tilePos(vec(0, 0), 'cbr'),
    tilePos(vec(1, 0), 'cb'),
    tilePos(vec(1, 0), 'center'),
  ],
  srbay0_shelf1: [
    tilePos(vec(0, 0), 'center'),
    tilePos(vec(0, 0), 'cr'),
    tilePos(vec(0, 1), 'cbr'),
    tilePos(vec(1, 1), 'cb'),
    tilePos(vec(1, 1), 'center'),
  ],
  srbay0_shelf2: [
    tilePos(vec(0, 0), 'center'),
    tilePos(vec(0, 0), 'cr'),
    tilePos(vec(0, 2), 'cbr'),
    tilePos(vec(1, 2), 'cb'),
    tilePos(vec(1, 2), 'center'),
  ],
  srbay0_shelf3: [
    tilePos(vec(0, 0), 'center'),
    tilePos(vec(0, 0), 'cr'),
    tilePos(vec(0, 3), 'cbr'),
    tilePos(vec(1, 3), 'cb'),
    tilePos(vec(1, 3), 'center'),
  ],
  srbay0_shelf4: [
    tilePos(vec(0, 0), 'center'),
    tilePos(vec(0, 0), 'cr'),
    tilePos(vec(0, 0), 'cbr'),
    tilePos(vec(2, 0), 'cb'),
    tilePos(vec(2, 0), 'center'),
  ],
  srbay0_shelf5: [
    tilePos(vec(0, 0), 'center'),
    tilePos(vec(0, 0), 'cr'),
    tilePos(vec(0, 1), 'cbr'),
    tilePos(vec(2, 1), 'cb'),
    tilePos(vec(2, 1), 'center'),
  ],
  srbay0_shelf6: [
    tilePos(vec(0, 0), 'center'),
    tilePos(vec(0, 0), 'cr'),
    tilePos(vec(0, 2), 'cbr'),
    tilePos(vec(2, 2), 'cb'),
    tilePos(vec(2, 2), 'center'),
  ],
  srbay0_shelf7: [
    tilePos(vec(0, 0), 'center'),
    tilePos(vec(0, 0), 'cr'),
    tilePos(vec(0, 3), 'cbr'),
    tilePos(vec(2, 3), 'cb'),
    tilePos(vec(2, 3), 'center'),
  ],
  srbay1_shelf0: [
    tilePos(vec(0, 1), 'center'),
    tilePos(vec(0, 1), 'cr'),
    tilePos(vec(0, 0), 'cbr'),
    tilePos(vec(1, 0), 'cb'),
    tilePos(vec(1, 0), 'center'),
  ],
  srbay1_shelf1: [
    tilePos(vec(0, 1), 'center'),
    tilePos(vec(0, 1), 'cr'),
    tilePos(vec(0, 1), 'cbr'),
    tilePos(vec(1, 1), 'cb'),
    tilePos(vec(1, 1), 'center'),
  ],
  srbay1_shelf2: [
    tilePos(vec(0, 1), 'center'),
    tilePos(vec(0, 1), 'cr'),
    tilePos(vec(0, 2), 'cbr'),
    tilePos(vec(1, 2), 'cb'),
    tilePos(vec(1, 2), 'center'),
  ],
  srbay1_shelf3: [
    tilePos(vec(0, 1), 'center'),
    tilePos(vec(0, 1), 'cr'),
    tilePos(vec(0, 3), 'cbr'),
    tilePos(vec(1, 3), 'cb'),
    tilePos(vec(1, 3), 'center'),
  ],
  srbay1_shelf4: [
    tilePos(vec(0, 1), 'center'),
    tilePos(vec(0, 1), 'cr'),
    tilePos(vec(0, 0), 'cbr'),
    tilePos(vec(2, 0), 'cb'),
    tilePos(vec(2, 0), 'center'),
  ],
  srbay1_shelf5: [
    tilePos(vec(0, 1), 'center'),
    tilePos(vec(0, 1), 'cr'),
    tilePos(vec(0, 1), 'cbr'),
    tilePos(vec(2, 1), 'cb'),
    tilePos(vec(2, 1), 'center'),
  ],
  srbay1_shelf6: [
    tilePos(vec(0, 1), 'center'),
    tilePos(vec(0, 1), 'cr'),
    tilePos(vec(0, 2), 'cbr'),
    tilePos(vec(2, 2), 'cb'),
    tilePos(vec(2, 2), 'center'),
  ],
  srbay1_shelf7: [
    tilePos(vec(0, 1), 'center'),
    tilePos(vec(0, 1), 'cr'),
    tilePos(vec(0, 3), 'cbr'),
    tilePos(vec(2, 3), 'cb'),
    tilePos(vec(2, 3), 'center'),
  ],
  srbay2_shelf0: [
    tilePos(vec(0, 2), 'center'),
    tilePos(vec(0, 2), 'cr'),
    tilePos(vec(0, 0), 'cbr'),
    tilePos(vec(1, 0), 'cb'),
    tilePos(vec(1, 0), 'center'),
  ],
  srbay2_shelf1: [
    tilePos(vec(0, 2), 'center'),
    tilePos(vec(0, 2), 'cr'),
    tilePos(vec(0, 1), 'cbr'),
    tilePos(vec(1, 1), 'cb'),
    tilePos(vec(1, 1), 'center'),
  ],
  srbay2_shelf2: [
    tilePos(vec(0, 2), 'center'),
    tilePos(vec(0, 2), 'cr'),
    tilePos(vec(0, 2), 'cbr'),
    tilePos(vec(1, 2), 'cb'),
    tilePos(vec(1, 2), 'center'),
  ],
  srbay2_shelf3: [
    tilePos(vec(0, 2), 'center'),
    tilePos(vec(0, 2), 'cr'),
    tilePos(vec(0, 3), 'cbr'),
    tilePos(vec(1, 3), 'cb'),
    tilePos(vec(1, 3), 'center'),
  ],
  srbay2_shelf4: [
    tilePos(vec(0, 2), 'center'),
    tilePos(vec(0, 2), 'cr'),
    tilePos(vec(0, 0), 'cbr'),
    tilePos(vec(2, 0), 'cb'),
    tilePos(vec(2, 0), 'center'),
  ],
  srbay2_shelf5: [
    tilePos(vec(0, 2), 'center'),
    tilePos(vec(0, 2), 'cr'),
    tilePos(vec(0, 1), 'cbr'),
    tilePos(vec(2, 1), 'cb'),
    tilePos(vec(2, 1), 'center'),
  ],
  srbay2_shelf6: [
    tilePos(vec(0, 2), 'center'),
    tilePos(vec(0, 2), 'cr'),
    tilePos(vec(0, 2), 'cbr'),
    tilePos(vec(2, 2), 'cb'),
    tilePos(vec(2, 2), 'center'),
  ],
  srbay2_shelf7: [
    tilePos(vec(0, 2), 'center'),
    tilePos(vec(0, 2), 'cr'),
    tilePos(vec(0, 3), 'cbr'),
    tilePos(vec(2, 3), 'cb'),
    tilePos(vec(2, 3), 'center'),
  ],
  srbay3_shelf0: [
    tilePos(vec(0, 3), 'center'),
    tilePos(vec(0, 3), 'cr'),
    tilePos(vec(0, 0), 'cbr'),
    tilePos(vec(1, 0), 'cb'),
    tilePos(vec(1, 0), 'center'),
  ],
  srbay3_shelf1: [
    tilePos(vec(0, 3), 'center'),
    tilePos(vec(0, 3), 'cr'),
    tilePos(vec(0, 1), 'cbr'),
    tilePos(vec(1, 1), 'cb'),
    tilePos(vec(1, 1), 'center'),
  ],
  srbay3_shelf2: [
    tilePos(vec(0, 3), 'center'),
    tilePos(vec(0, 3), 'cr'),
    tilePos(vec(0, 2), 'cbr'),
    tilePos(vec(1, 2), 'cb'),
    tilePos(vec(1, 2), 'center'),
  ],
  srbay3_shelf3: [
    tilePos(vec(0, 3), 'center'),
    tilePos(vec(0, 3), 'cr'),
    tilePos(vec(0, 3), 'cbr'),
    tilePos(vec(1, 3), 'cb'),
    tilePos(vec(1, 3), 'center'),
  ],
  srbay3_shelf4: [
    tilePos(vec(0, 3), 'center'),
    tilePos(vec(0, 3), 'cr'),
    tilePos(vec(0, 0), 'cbr'),
    tilePos(vec(2, 0), 'cb'),
    tilePos(vec(2, 0), 'center'),
  ],
  srbay3_shelf5: [
    tilePos(vec(0, 3), 'center'),
    tilePos(vec(0, 3), 'cr'),
    tilePos(vec(0, 1), 'cbr'),
    tilePos(vec(2, 1), 'cb'),
    tilePos(vec(2, 1), 'center'),
  ],
  srbay3_shelf6: [
    tilePos(vec(0, 3), 'center'),
    tilePos(vec(0, 3), 'cr'),
    tilePos(vec(0, 2), 'cbr'),
    tilePos(vec(2, 2), 'cb'),
    tilePos(vec(2, 2), 'center'),
  ],
  srbay3_shelf7: [
    tilePos(vec(0, 3), 'center'),
    tilePos(vec(0, 3), 'cr'),
    tilePos(vec(0, 3), 'cbr'),
    tilePos(vec(2, 3), 'cb'),
    tilePos(vec(2, 3), 'center'),
  ],
} as const;
